import './globals.css'
import { Inter } from 'next/font/google'
import { Nunito } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
